# Site settings
title: "Praying for Tamara"
email: "zblackwo@gmail.com"
description: "Praying for Tamara Noell"
baseurl: "/tamara/"
url: https://blackary.github.io/tamara/
title_description: "In this you rejoice, though now for a little while, if necessary, you have been grieved by various trials, so that the tested genuineness of your faith—more precious than gold that perishes though it is tested by fire—may be found to result in praise and glory and honor at the revelation of Jesus Christ."
title_image: /tamara/assets/t_and_s.jpg
google_analytics: "UA-20365477-4"
disqus_account: praying-for-tamara
github_repository: https://github.com/blackary/tamara/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: 
github_username:  blackary
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: 
footer_right: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
